services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build : ./requirements/mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb_volume:/var/lib/mysql
    expose:
      - 3306
    # restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build: ./requirements/wordpress
    env_file:
      - ./.env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    expose:
      - 9000
    # restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception
    env_file:
      - ./.env
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_volume:/var/www/html
    # restart: on-failure

volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /home/chagilan/data/wordpress
      o: bind
      type: none
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /home/chagilan/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge